<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AA-PC" ignored="1" name="defult" tests="8" failures="1" timestamp="20 Aug 2019 06:37:02 GMT" time="0.14" errors="0">
  <testcase name="tc001" time="0.072" classname="framework_testng.Groups.TestSuite1"/>
  <testcase name="tc002" time="0.005" classname="framework_testng.Groups.TestSuite1"/>
  <testcase name="tc003" time="0.002" classname="framework_testng.Groups.TestSuite1"/>
  <testcase name="tc005" time="0.001" classname="framework_testng.Groups.TestSuite2"/>
  <testcase name="tc004" time="0.014" classname="framework_testng.Groups.TestSuite2"/>
  <testcase name="tc007" time="0.003" classname="framework_testng.Groups.TestSuite3">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at framework_testng.Groups.TestSuite3.tc007(TestSuite3.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- tc007 -->
  <testcase name="tc008" time="0.001" classname="framework_testng.Groups.TestSuite3"/>
  <testcase name="tc009" time="0.0" classname="framework_testng.Groups.TestSuite3">
    <skipped/>
  </testcase> <!-- tc009 -->
  <testcase name="tc006" time="0.0" classname="framework_testng.Groups.TestSuite2">
    <ignored/>
  </testcase> <!-- tc006 -->
</testsuite> <!-- defult -->
