<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AA-PC" ignored="0" name="Default test" tests="8" failures="1" timestamp="19 Aug 2019 07:05:35 GMT" time="0.166" errors="0">
  <testcase name="Browser_launch" time="0.007" classname="framework_testng.Testng_Method_Dependencies"/>
  <testcase name="App_Load" time="0.001" classname="framework_testng.Testng_Method_Dependencies"/>
  <testcase name="User_login" time="0.003" classname="framework_testng.Testng_Method_Dependencies"/>
  <testcase name="ComposeEmail" time="0.003" classname="framework_testng.Testng_Method_Dependencies">
    <failure type="java.lang.AssertionError" message="expected [msg] but found [emsg]">
      <![CDATA[java.lang.AssertionError: expected [msg] but found [emsg]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at framework_testng.Testng_Method_Dependencies.ComposeEmail(Testng_Method_Dependencies.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- ComposeEmail -->
  <testcase name="Search_email" time="0.004" classname="framework_testng.Testng_Method_Dependencies"/>
  <testcase name="Verify_Email_At_inbox" time="0.007" classname="framework_testng.Testng_Method_Dependencies"/>
  <testcase name="Verify_Email_At_Sentemails" time="0.0" classname="framework_testng.Testng_Method_Dependencies">
    <skipped/>
  </testcase> <!-- Verify_Email_At_Sentemails -->
  <testcase name="User_Signout" time="0.001" classname="framework_testng.Testng_Method_Dependencies"/>
</testsuite> <!-- Default test -->
