<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="AA-PC" name="framework_testng.Test_listners.MyTest" tests="8" failures="1" timestamp="22 Aug 2019 08:19:16 GMT" time="0.042" errors="0">
  <testcase name="tc004" time="0.000" classname="framework_testng.Test_listners.MyTest"/>
  <testcase name="tc006" time="0.001" classname="framework_testng.Test_listners.MyTest"/>
  <testcase name="tc003" time="0.001" classname="framework_testng.Test_listners.MyTest">
    <skipped/>
  </testcase> <!-- tc003 -->
  <testcase name="tc001" time="0.036" classname="framework_testng.Test_listners.MyTest"/>
  <testcase name="tc002" time="0.002" classname="framework_testng.Test_listners.MyTest">
    <failure type="java.lang.AssertionError" message="expected [google] but found [gmail]">
      <![CDATA[java.lang.AssertionError: expected [google] but found [gmail]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at framework_testng.Test_listners.MyTest.tc002(MyTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- tc002 -->
  <testcase name="tc005" time="0.001" classname="framework_testng.Test_listners.MyTest">
    <skipped/>
  </testcase> <!-- tc005 -->
  <testcase name="tc006" time="0.001" classname="framework_testng.Test_listners.MyTest"/>
  <testcase name="tc006" time="0.000" classname="framework_testng.Test_listners.MyTest"/>
</testsuite> <!-- framework_testng.Test_listners.MyTest -->
